[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "^6.10.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.0"
